version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    expose:
      - 8000
    command: gunicorn -w 8 -b 0.0.0.0:8000 --log-file /app/logs/gunicorn.log --log-level=DEBUG app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - flask_app

  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./elasticsearch/config/:/usr/share/elasticsearch/config/
    environment:
      - "cluster.name=elasticsearch"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "XPACK_SECURITY_ENABLED=false"
    healthcheck:
      test: "curl http://elasticsearch:9200"
      interval: "1s"
      timeout: "3s"
      retries: 60
    restart: always
    expose:
      - 9200
    ports:
      - "9200:9200"


    # depends_on:
    #   - flask_app
# version: "3"
# services:


#   backend:
#     build:
#       context: ./flask_app
#       dockerfile: Dockerfile
#     networks:
#       - backend
#     restart: always
#     ports:
#       - "8005:8005"

# networks:
#   backend:
