version: "3"

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    expose:
      - "3000"
    command: gunicorn -w 8 -b :3000 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - flask_app
# version: "3"
# services:
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
#     networks:
#       - backend
#     restart: always
#     volumes:
#       - ./ES_DATA:/usr/share/elasticsearch/data
#     environment:
#       - discovery.type=single-node
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ports:
#       - "9200:9200"

#   backend:
#     build:
#       context: ./flask_app
#       dockerfile: Dockerfile
#     networks:
#       - backend
#     restart: always
#     ports:
#       - "8005:8005"

# networks:
#   backend:
