# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:7.8.0
# COPY config .

# # Install the requirements in the current directory.
# RUN pip install -r requirements.txt

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu